# Pre-commit hooks for Langfuse Deployment Security
# Focused on preventing accidental secret exposure to public GitHub
# Install: pip install pre-commit && pre-commit install
# Manual scan: pre-commit run --all-files

repos:
  # Gitleaks - Primary secret detection
  # Scans for passwords, API keys, tokens, and other secrets
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.0
    hooks:
      - id: gitleaks
        name: Detect secrets with Gitleaks
        description: Scan for hardcoded secrets, API keys, and passwords

  # Standard security and file hygiene checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Security-critical checks
      - id: detect-private-key
        name: Detect private keys
        description: Prevent SSH/GPG private keys from being committed

      # File integrity checks
      - id: check-added-large-files
        name: Check for large files
        args: ['--maxkb=1000']
        description: Prevent large files (>1MB) from being accidentally committed

      - id: check-case-conflict
        name: Check for case conflicts
        description: Check for files that would conflict in case-insensitive filesystems

      - id: check-merge-conflict
        name: Check for merge conflicts
        description: Prevent committing files with merge conflict markers

      # YAML/JSON validation (important for docker-compose and configs)
      - id: check-yaml
        name: Validate YAML files
        args: ['--unsafe']  # Allow custom tags like !reference
        exclude: '^compose/docker-compose\.backup\.yml$'

      - id: check-json
        name: Validate JSON files

      # Code hygiene
      - id: end-of-file-fixer
        name: Fix end of file
        description: Ensure files end with a newline

      - id: trailing-whitespace
        name: Trim trailing whitespace
        description: Remove trailing whitespace from lines

      - id: mixed-line-ending
        name: Fix mixed line endings
        args: ['--fix=lf']
        description: Ensure consistent line endings (LF)

# Configuration
default_language_version:
  python: python3

# Stages configuration
default_stages: [pre-commit, pre-push]

# Additional settings
fail_fast: false  # Run all hooks even if one fails
verbose: true     # Show output from hooks
