# Memory Intelligence Layer Services
# Extends the base Langfuse deployment with memory observability

version: '3.9'

services:
  # Memory Intelligence API Service
  memory-intelligence:
    build:
      context: ..
      dockerfile: Dockerfile.memory
    container_name: langfuse-memory-intelligence
    environment:
      # Langfuse Configuration
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY}
      LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY}
      LANGFUSE_HOST: http://langfuse-web:3000

      # Neo4j Configuration for Graphiti
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: ${NEO4J_USER:-neo4j}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}

      # OpenAI Configuration
      OPENAI_API_KEY: ${OPENAI_API_KEY}

      # Service Configuration
      MEMORY_CACHE_TTL: 60
      ENABLE_AB_TESTING: true
      ENABLE_AUTO_EVALUATION: true

    volumes:
      - ../config/prompts:/app/config/prompts:ro
      - ../src:/app/src:ro
      - memory-cache:/app/cache

    networks:
      - langfuse-network

    depends_on:
      langfuse-web:
        condition: service_healthy
      neo4j:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

    labels:
      - "dev.orbstack.domains=memory.langfuse.local"

  # Neo4j for Graphiti Memory Storage
  neo4j:
    image: neo4j:5.15.0
    container_name: langfuse-neo4j
    environment:
      NEO4J_AUTH: ${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD}
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_dbms_memory_pagecache_size: 1G
      NEO4J_dbms_memory_heap_max__size: 1G

    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs

    ports:
      - "7474:7474"  # Browser
      - "7687:7687"  # Bolt

    networks:
      - langfuse-network

    healthcheck:
      test: ["CMD", "neo4j", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

    labels:
      - "dev.orbstack.domains=neo4j.langfuse.local"

  # Evaluation Runner Service
  evaluation-runner:
    build:
      context: ..
      dockerfile: Dockerfile.evaluator
    container_name: langfuse-evaluation-runner
    environment:
      LANGFUSE_PUBLIC_KEY: ${LANGFUSE_PUBLIC_KEY}
      LANGFUSE_SECRET_KEY: ${LANGFUSE_SECRET_KEY}
      LANGFUSE_HOST: http://langfuse-web:3000
      OPENAI_API_KEY: ${OPENAI_API_KEY}

      # Evaluation Configuration
      RUN_INTERVAL_MINUTES: 60
      MIN_EFFECTIVENESS_THRESHOLD: 0.7
      AUTO_PROMOTE_THRESHOLD: 0.85

    volumes:
      - ../config/prompts:/app/config/prompts:ro
      - ../src:/app/src:ro
      - evaluation-results:/app/results

    networks:
      - langfuse-network

    depends_on:
      - memory-intelligence

    labels:
      - "dev.orbstack.domains=evaluator.langfuse.local"

volumes:
  neo4j-data:
    driver: local
  neo4j-logs:
    driver: local
  memory-cache:
    driver: local
  evaluation-results:
    driver: local

networks:
  langfuse-network:
    external: true
    name: langfuse-prod_default
