# Memory Search Prompt Templates
# These are fallback templates used when Langfuse is unavailable
# Production versions are managed in Langfuse Prompt Management

memory_search_exact:
  prompt: |
    Search the knowledge graph for memories matching this query:
    Query: {{query}}

    Context:
    - Current GTD Task: {{gtd_task}}
    - Session Type: {{session_type}}
    - Priority: Exact matches and recent solutions

    Return memories with:
    - Exact command matches
    - Specific error messages
    - Technical configurations

    Include confidence scores and temporal weights.
  config:
    model: gpt-4o
    temperature: 0.1
    max_tokens: 2000

memory_search_semantic:
  prompt: |
    Find conceptually related memories for:
    Query: {{query}}

    Context:
    - Domain: {{domain}}
    - Related Concepts: {{concepts}}
    - Time Range: {{time_range}}

    Search for:
    - Similar problems and solutions
    - Related patterns
    - Conceptual connections

    Prioritize by relevance and success rate.
  config:
    model: gpt-4o
    temperature: 0.3
    max_tokens: 2000

memory_search_cross_domain:
  prompt: |
    Discover cross-domain insights between GTD and coding:
    Query: {{query}}

    GTD Context:
    - Active Projects: {{gtd_projects}}
    - Current Phase: {{gtd_phase}}
    - Energy Level: {{energy_level}}

    Coding Context:
    - Technology Stack: {{tech_stack}}
    - Problem Domain: {{problem_domain}}
    - Recent Errors: {{recent_errors}}

    Find connections between:
    - Task management patterns and code organization
    - Project planning and system architecture
    - Energy cycles and debugging effectiveness

    Return insights that bridge both domains.
  config:
    model: gpt-4o
    temperature: 0.5
    max_tokens: 3000
